version: 0.2

phases:
  install:
    commands:
      - pip install -r meter-loader/requirements.txt -t meter-loader

artifacts:
  base-directory: meter-loader
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
