version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-500/requirements.txt -t mdf-500

artifacts:
  base-directory: mdf-500
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
