version: 0.2

phases:
  install:
    commands:
      - pip install -r nem/requirements.txt -t nem

artifacts:
  base-directory: nem
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
