version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-100/requirements.txt -t mdf-100

artifacts:
  base-directory: mdf-100
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
