version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-300/requirements.txt -t mdf-300

artifacts:
  base-directory: mdf-300
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
