version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-200/requirements.txt -t mdf-200

artifacts:
  base-directory: mdf-200
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
