AWSTemplateFormatVersion: "2010-09-09"
Description: Template to build lambdas and dependencies for lambdas

Parameters:

  SourceLocation:
    Type: String
    Description: S3 bucket path where the original source code (and cfn config) is stored

  MDF500Location:
    Type: String
    Description: S3 bucket path where the built mdf_500 lambda is stored

  MDF500Key:
    Type: String
    Description: S3 key where the built mdf_500 lambda is stored

  MDF900Location:
    Type: String
    Description: S3 bucket path where the built mdf_900 lambda is stored

  MDF900Key:
    Type: String
    Description: S3 key where the built mdf_900 lambda is stored

  MDF250Location:
    Type: String
    Description: S3 bucket path where the built mdf_250 lambda is stored

  MDF250Key:
    Type: String
    Description: S3 key where the built mdf_250 lambda is stored

  MDF550Location:
    Type: String
    Description: S3 bucket path where the built mdf_550 lambda is stored

  MDF550Key:
    Type: String
    Description: S3 key where the built mdf_550 lambda is stored

  Name:
    Type: String
    Description: Name of the stack

Resources:

  MeterDataLoaderDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "meterdataloader-dlq"

  MeterDataLoaderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "meterdataloader-queue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt [MeterDataLoaderDLQ, Arn]
        maxReceiveCount: 5

  MeterDataLoaderTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "meterdataloader-topic"
      TopicName: "meteredataloader-topic"
      Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "MeterDataLoaderQueue"
              - "Arn"
          Protocol: 'sqs'

  MeterDataLoaderQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref 'MeterDataLoaderQueue']
      PolicyDocument:
        Version: "2012-10-17"
        Id: MeterDataLoaderQueuePolicy
        Statement:
          - Resource:
              - Fn::GetAtt:
                - "MeterDataLoaderQueue"
                - "Arn"
            Effect: "Allow"
            Sid: "Allow-User-SendMessage"
            Action:
              - "sqs:SendMessage"
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MeterDataLoaderTopic
            Principal:
              AWS: "*"

  LambdaRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: LambdaRequired
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LambdaPolicy
                Action:
                  - 's3:*'
                  - 'sns:*'
                  - 'lambda:*'
                Effect: Allow
                Resource: '*'
              - Sid: CloudWatchWriteLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MDF500Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'MeterDataLoaderArtifactsBucket'
        S3Key: !Ref MDF500Key
      FunctionName: "mdf_500"
      Handler: "mdf_500.handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 300

  MDF900Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'MeterDataLoaderArtifactsBucket'
        S3Key: !Ref MDF900Key
      FunctionName: "mdf_900"
      Handler: "mdf_900.handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 300

  MDF250Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'MeterDataLoaderArtifactsBucket'
        S3Key: !Ref MDF250Key
      FunctionName: "mdf_250"
      Handler: "mdf_250.handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 300

  MDF550Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'MeterDataLoaderArtifactsBucket'
        S3Key: !Ref MDF550Key
      FunctionName: "mdf_550"
      Handler: "mdf_550.handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 300

  MeterDataLoaderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "meterdataloader-bucket.${AWS::StackName}"

  MDF500InputBucket:
    Type: AWS::S3::Bucket
    DependsOn: MDF500InputBucketPermission
    Properties:
      BucketName: !Sub "mdf-500-${AWS::StackName}.input"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt MDF500Lambda.Arn

  MDF500InputBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MDF500Lambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::mdf-500-${AWS::StackName}.input"

  MDF500ProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-500-${AWS::StackName}.processing"

  MDF500DoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-500-${AWS::StackName}.done"

  MDF900InputBucket:
    Type: AWS::S3::Bucket
    DependsOn: MDF900InputBucketPermission
    Properties:
      BucketName: !Sub "mdf-900-${AWS::StackName}.input"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt MDF900Lambda.Arn

  MDF900InputBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MDF900Lambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::mdf-900-${AWS::StackName}.input"

  MDF900ProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-900-${AWS::StackName}.processing"

  MDF900DoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-900-${AWS::StackName}.done"

  MDF250InputBucket:
    Type: AWS::S3::Bucket
    DependsOn: MDF250InputBucketPermission
    Properties:
      BucketName: !Sub "mdf-250-${AWS::StackName}.input"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt MDF250Lambda.Arn

  MDF250InputBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MDF250Lambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::mdf-250-${AWS::StackName}.input"

  MDF250ProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-250-${AWS::StackName}.processing"

  MDF250DoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-250-${AWS::StackName}.done"

  MDF550InputBucket:
    Type: AWS::S3::Bucket
    DependsOn: MDF550InputBucketPermission
    Properties:
      BucketName: !Sub "mdf-550-${AWS::StackName}.input"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt MDF550Lambda.Arn

  MDF550InputBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MDF550Lambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::mdf-550-${AWS::StackName}.input"

  MDF550ProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-550-${AWS::StackName}.processing"

  MDF550DoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mdf-550-${AWS::StackName}.done"

Outputs:

  MeterDataLoaderDLQURL:
    Description: "URL of DLQ"
    Value:
      Ref: MeterDataLoaderDLQ

  MeterDataLoaderDLQArn:
    Description: "Arn of DLQ"
    Value:
      !GetAtt [MeterDataLoaderDLQ, Arn]

  MeterDataLoaderQueueURL:
    Description: "URL of meterdataloader-queue"
    Value:
      Ref: MeterDataLoaderQueue

  MeterDataLoaderQueueArn:
    Description: "Arn of meterdataloader-queue"
    Value:
      !GetAtt [MeterDataLoaderQueue, Arn]

  MeterDataLoaderTopicArn:
    Description: "Arn of meterdataloader-topic"
    Value:
      Ref: MeterDataLoaderTopic

  MDF500InputBucketArn:
    Description: "Arn of MDF500InputBucket"
    Value:
      !GetAtt [MDF500InputBucket, Arn]
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MDF500InputBucket ] ]

  MDF500ProcessingBucketArn:
    Description: "Arn of MDF500ProcessingBucket"
    Value:
      !GetAtt [MDF500ProcessingBucket, Arn]

  MDF500DoneBucketArn:
    Description: "Arn of MDF500DoneBucket"
    Value:
      !GetAtt [MDF500DoneBucket, Arn]

  MDF900InputBucketArn:
    Description: "Arn of MDF900InputBucket"
    Value:
      !GetAtt [MDF900InputBucket, Arn]
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MDF900InputBucket ] ]

  MDF900ProcessingBucketArn:
    Description: "Arn of MDF900ProcessingBucket"
    Value:
      !GetAtt [MDF900ProcessingBucket, Arn]

  MDF900DoneBucketArn:
    Description: "Arn of MDF900DoneBucket"
    Value:
      !GetAtt [MDF900DoneBucket, Arn]

  MDF250InputBucketArn:
    Description: "Arn of MDF250InputBucket"
    Value:
      !GetAtt [MDF250InputBucket, Arn]
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MDF250InputBucket ] ]

  MDF250ProcessingBucketArn:
    Description: "Arn of MDF250ProcessingBucket"
    Value:
      !GetAtt [MDF250ProcessingBucket, Arn]

  MDF250DoneBucketArn:
    Description: "Arn of MDF250DoneBucket"
    Value:
      !GetAtt [MDF250DoneBucket, Arn]

  MDF550InputBucketArn:
    Description: "Arn of MDF550InputBucket"
    Value:
      !GetAtt [MDF550InputBucket, Arn]
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MDF550InputBucket ] ]

  MDF550ProcessingBucketArn:
    Description: "Arn of MDF550ProcessingBucket"
    Value:
      !GetAtt [MDF550ProcessingBucket, Arn]

  MDF550DoneBucketArn:
    Description: "Arn of MDF550DoneBucket"
    Value:
      !GetAtt [MDF550DoneBucket, Arn]
