version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r meter-loader-partition/requirements.txt -t meter-loader-partition

artifacts:
  base-directory: meter-loader-partition
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
