version: 0.2

phases:
  install:
    commands:
      - pip install -r meter-loader-nem/requirements.txt -t meter-loader-nem

artifacts:
  base-directory: meter-loader-nem
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
