version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-550/requirements.txt -t mdf-550

artifacts:
  base-directory: mdf-550
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
