version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-250/requirements.txt -t mdf-250

artifacts:
  base-directory: mdf-250
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
