version: 0.2

phases:
  install:
    commands:
      - pip install -r mdf-900/requirements.txt -t mdf-900

artifacts:
  base-directory: mdf-900
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
